### PR TITLE
Added defaultSourceRoot option to sourcemaps.write

### PR DESCRIPTION
**Pull request by tniswong**
I didn't like how my sass and javascript sources were under the same root, so I added the option to specify the roots. Let me know if you don't like the naming, I'm happy to change it.

### CODE REVIEW

**Comment by Francisc** [comment]
I like this. Hopefully the project isn't dead, there hasn't been much activity here.

**Comment by nmccready** [comment]
@tniswong rebase and I'll merge

**Comment by nmccready** [comment]
This might be easier for me to just merge this manually.

**Comment by nmccready** [comment]
Therefore this is approved to merge against 1.X

**Comment by nmccready** [comment]
closing since no feedback

**Pull request closed without merging**
