### PR TITLE
removed es6 code

### PR DESCRIPTION
**Pull request by rcodonnell**
My application is fail currently because of this change. I reverted the code back to es5 to allow our application to work while we still use an older node version. Please let me know that this is okay.

### CODE REVIEW

**Comment by nmccready** [comment]
It required way more than just that. I am currently fixing it. 8ecaa7320d0c656514dfc07b15611d682f757818

**Comment by nmccready** [comment]
Also 2.X does not support node 0.X . So please target 1.X .

**Comment by rcodonnell** [comment]
I thought it was targeting 1.X

**Comment by nmccready** [comment]
No worries, it should be resolved now for version 1.7.3 . If you would like to confirm please do so.

**Comment by rcodonnell** [comment]
Works now, perfect. Thank you

**Pull request closed without merging**
