### PR TITLE
add relativeToSourcePath to options

### PR DESCRIPTION
**Pull request by sixinli**
instead of using an absolute path, this option adds the ability to specify a relative file
from the dest file to the src file, for example:

i have:
src/myFolder1/someFile.ts

and my build files:
build/src/myFolder1/someFile.js
build/src/myFolder1/someFile.js.map

the source path would be "../../../src/myFolder1/someFile.ts"

### CODE REVIEW

**Comment by Emigre** [comment]
I've just opened a PR for this PR as sixinli/gulp-sourcemaps/pull/1

**Comment by sixinli** [comment]
@Emigre thanks! i have modified the test accordingly

**Comment by Emigre** [comment]
great, thanks!

**Comment by nmccready** [comment]
Is this still desired even with #157 ?

**Comment by nmccready** [comment]
closing since no feedback

**Pull request closed without merging**
