### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by shinnn**
No breaking changes

### CODE REVIEW

**Comment by TrySound** [comment]
+1

**Comment by floridoo** [comment]
Updated in 958f86ccf0035e55234dc35668cec1654a05a860

**Comment by shinnn** [comment]
Oh, thanks. I added some useful advises to the commit. https://github.com/floridoo/gulp-sourcemaps/commit/958f86ccf0035e55234dc35668cec1654a05a860

**Pull request closed without merging**
