### PR TITLE
Add test integration with gulp-rev

### PR DESCRIPTION
**Pull request by NamPNQ**

### CODE REVIEW

**Comment by nmccready** [comment]
@NamPNQ I was able to `cherry-pick` the code to 1.X anyway I reverted the file clone stuff and your spec still fails. So I am not sure of the difference.

```
@@@@@@@@@@@@ revOrigPath @@@@@@@@@@@@
path: /Users/nem/code/github/rmaps/gulp-sourcemaps/test/maps/helloworld-39b981243f.js.map
revOrigPath: undefined
not ok 77 Have correct origin path
  ---
    operator: ok
    expected: true
    actual:   false
    at: DestroyableTransform.<anonymous> (/Users/nem/code/github/rmaps/gulp-sourcemaps/test/write.js:618:9)
  ...
```

**Comment by nmccready** [comment]
Now undefined makes sense, but I don't see how we're messing with gulp-rev in either case.

**Comment by nmccready** [comment]
@NamPNQ see https://github.com/realtymaps/gulp-sourcemaps/commit/ceb55e67f16f238d164f5854d4390d94fe4f4b8f and it still fails.

**Comment by NamPNQ** [comment]
@nmccready I had update for old version
as i mention, `gulp-rev-replace` will check if `file.revOrigPath` then it replace content have text `file.revOrigPath` to `file.path`, in this case `file.revOrigPath` of `blabla.js.map` is `blabla.js` instead of `blabla.js.map` or `undefined`

**Comment by nmccready** [comment]
@NamPNQ to make a 1.X PR you'll need to chery-pick all your changes/commits individualy. Or work off my branch in realtymaps

**Comment by nmccready** [comment]
Need more feedback. Closing for now as I am not convinced this is needed.

**Pull request closed without merging**
