### PR TITLE
Fix the detect newline showing null in text :: fix-null-newline-1.x

### PR DESCRIPTION
**Pull request by TerryMooreII**
Here is the pull request fixing the newline returning null when a newline character is not found branching and merging to the 1.x branch.  I took a look at creating a test for this but honestly I am not sure how to in this testing framework. Can you assist me with this?

### CODE REVIEW

**Comment by gzzz** [comment]
detectNewline mostly returns null because file was minified and all linebreacks already removed.
I think instead of use hard '\n' (detectNewline.graceful) better detect newline symbol in init() function, not in write() function.

In this case detectNewline successfully detects new line symbol.

**Comment by nmccready** [comment]
@gzz so your suggesting the detectNewLine functionality to init correct?

**Comment by gzzz** [comment]
@nmccready, yes.

**Comment by nmccready** [comment]
@gzzz open a new issue if you feel this is necessary. 

Your suggestion means messing with [commentFormatter](https://github.com/floridoo/gulp-sourcemaps/blob/master/src/write.js#L99-L116). Also a lot of the comments can be potentially removed in [init](https://github.com/floridoo/gulp-sourcemaps/blob/master/src/init.js#L54-L64), so I am not so sure about this. Anyway a PR or commit would help me see what your idea is.

**Pull request merged**
