### PR TITLE
Updating packages

### PR DESCRIPTION
**Pull request by lipis**
All the tests are green!

### CODE REVIEW

**Comment by lipis** [comment]
So shall we expect a release soon?!

**Comment by nmccready** [comment]
@lipis I just got perms to merge PR's I do not know if @floridoo has given me perms to push to npm yet. If I do get those, I shall push a new version immediately.

**Comment by nmccready** [comment]
Also this issue is rather relevant to resolve before pushing a new version #225 . So if anyone else has answers please advise there.

**Comment by nmccready** [comment]
Released https://github.com/floridoo/gulp-sourcemaps/releases/tag/v1.7.0

**Comment by lipis** [comment]
Thank you!

**Comment by nmccready** [comment]
@lipis please note people spoke up too late regarding https://github.com/floridoo/gulp-sourcemaps/commit/2d8c319a5c8477a6e2f27ce42009b0109faa7421#commitcomment-19367684

**Comment by nmccready** [comment]
We are currently trying to decide how to proceed.

**Comment by lipis** [comment]
oups.. good luck guys!

**Comment by nmccready** [comment]
1.7.1 was pushed

**Comment by lipis** [comment]
and the world is back to normal again :)

**Comment by nmccready** [comment]
> and the world is back to normal again :)

🍻

**Pull request closed without merging**
